name: "Get a json file and post a comment"
description: "Add a label when a new PR is opened"
author: "Ghazian"

inputs:
  gh-token:
    description: "The Github token for authentication"
    required: true
  jsonfile:
    description: "File path for the json file"
    required: true

runs:
  using: "node16"
  main: "dist/index.js"
